elecciones/elecciones/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'', include('polls.urls')),

]

elecciones/polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Index.as_view(), name = 'index'),
	url(r'^login/$', views.acceso, name = 'login'),
	url(r'^logout/$', views.VistaLogout, name = 'logout'),
	url(r'^registro/$', views.newUser, name = 'registro'),


	url(r'^circunscripcion/$', views.CircunscripcionLista.as_view(), name = 'circunscripcion_url'),
	url(r'^circunscripcion/crear/$', views.CircunscripcionCrear.as_view(), name = 'circunscripcion_crear_url'),
	url(r'^circunscripcion/vistaDetallada/(?P<pk>.*)$', views.CircunscripcionDetalle.as_view(), name = 'circunscripcion_detalle_url'),
	url(r'^circunscripcion/editar/(?P<pk>.*)$', views.CircunscripcionEditar.as_view(), name = 'circunscripcion_editar_url'),
	url(r'^circunscripcion/eliminar/(?P<pk>.*)$', views.CircunscripcionEliminar.as_view(), name = 'circunscripcion_eliminar_url'),


	url(r'^mesa/$', views.MesaLista, name='mesa_url'),
    url(r'^mesa/vistaDetalladaMesa/(?P<pk>.*)$', views.MesaDetalle, name='mesa_detalle_url'),
   	url(r'^mesa/crear/$', views.MesaCrear, name='mesa_crear_url'),
    url(r'^mesa/editar/(?P<pk>.*)$', views.MesaEditar, name='mesa_editar_url'),
    url(r'^mesa/eliminar/(?P<pk>.*)$', views.MesaEliminar, name = 'mesa_eliminar_url'),


   	url(r'^resultado/$', views.ResultadoLista.as_view(), name='resultado_url'),
    url(r'^resultado/crear/$', views.ResultadoCrear.as_view(), name='resultado_crear_url'),
    url(r'^resultado/eliminar/(?P<pk>.*)$', views.ResultadoEliminar.as_view(), name = 'resultado_eliminar_url'),
	url(r'^resultado/editar/(?P<pk>.*)$', views.ResultadoEditar.as_view(), name = 'resultado_editar_url'),


	url(r'^partido/listar/$', views.PartidoListar.as_view(), name = 'partido_listar_url'),
	url(r'^partido/crear/$', views.GestionPartido.as_view(), name='partido_crear_url'),
    url(r'^partido/eliminar/(?P<pk>.*)$', views.PartidoDelete.as_view(), name = 'partido_eliminar_url'),
]

elecciones/polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.



class Circunscripcion(models.Model):
	nombre = models.CharField(max_length = 200, unique = True)
	nEscanos = models.IntegerField(default = 0)

	def __str__(self):
		return self.nombre

class Mesa(models.Model):
	nombre = models.CharField(max_length = 200, unique = True)
	circunscripcion = models.ForeignKey(Circunscripcion)

	def __str__(self):
		return self.nombre

class Partido(models.Model):
	nombre = models.CharField(max_length = 200, unique = True)

	def __str__(self):
		return self.nombre

class Resultado(models.Model):
	mesa = models.ForeignKey(Mesa)
	partido = models.ForeignKey(Partido)
	votos = models.IntegerField(default = 0)

	def __str__(self):
		return "El partido %s en la mesa %s tiene %d votos" % (self.partido, self.mesa, self.votos)

class UserProfile(models.Model):
	usuario = models.OneToOneField(settings.AUTH_USER_MODEL)

	def __unicode__(self):
		return self.usuario.username

elecciones/polls/forms.py
from django import forms
from .models import Mesa

class MesaForm(forms.ModelForm):
	class Meta:
		model = Mesa
		fields = ('nombre', 'circunscripcion',)

elecciones/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from .models import Circunscripcion, Mesa, Resultado, Partido
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect
from .forms import MesaForm
# Create your views here.

#no se usa esa view
def newUser(request):
	if request.method == 'POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			usuario = User.objects.get(username=form.cleaned_data['username'])
			user = UserProfile(usuario=usuario)
			user.save()
			return render(request, 'gracias.html', {'usuario': usuario})
	else:
		#si el method es GET, instanciamos un objeto RegistroUsuario vacio
		form=UserCreationForm()
	# Y mostramos los datos
	return render(request, 'registro.html', {'form':form})

def acceso(request):
	if  request.user.is_authenticated():
		return redirect('index')
	mensaje=''
	if request.method == 'POST':
		form = AuthenticationForm(request.POST)
		if form.is_valid:
			usuario = request.POST['username']
			password=request.POST['password']
			acceso=authenticate(username=usuario, password=password)
			if acceso is not None:
				if acceso.is_active:
					login(request, acceso)
					return redirect('index')
				else:
					return render(request, 'eleccion/no_activo.html')
			else:
				return render(request, 'eleccion/no_usuario.html')
	else:
		form = AuthenticationForm()
	return render(request, 'eleccion/login.html', {'form': form})

@login_required(login_url= 'login')
def VistaLogout(request):
	logout(request)
	return render(request, 'eleccion/logout.html')

class Index(TemplateView):
	template_name = "eleccion/index.html"

class GestionPartido(CreateView):
	template_name = "eleccion/formulario.html"
	model = Partido
	fields = ('nombre',)
	success_url = reverse_lazy('partido_listar_url')

	def get_context_data(self, **kwargs):
		#obtenemos el contextode la clase base
		context = super(GestionPartido, self).get_context_data(**kwargs)
		#anyadimos nuevas variables de contexto al diccionario
		context['titulo'] = 'Crear Partido'
		context['nombre_btn'] = 'Crear'
		#devolvemos el contexto
		return context

class PartidoListar(ListView):
	template_name = "eleccion/partido_listar.html"
	model = Partido

	def get_context_data(self, **kwargs):
		context = super(PartidoListar, self).get_context_data(**kwargs)
		context['partido_list'] = Partido.objects.all()[:10]
		return context

class PartidoDelete(DeleteView):
	template_name = "eleccion/partido_eliminar.html"
	model = Partido
	success_url = reverse_lazy('partido_listar_url')

	def dispatch(self, request, *args, **kwargs):
		if not request.user.has_perm('eleccion.delete_partido'):
			return redirect('login')
		return super(PartidoDelete, self).dispatch(request, *args, **kwargs)


class CircunscripcionLista(ListView):
	model = Circunscripcion
	template_name = "eleccion/circunscripcion.html"

	def get_context_data(self, **kwargs):
		context = super(CircunscripcionLista, self).get_context_data(**kwargs)
		context['object_list'] = Circunscripcion.objects.all()[:10]
		return context
		
class CircunscripcionCrear(CreateView):
	template_name = "eleccion/formulario.html"
	model = Circunscripcion
	fields = ('nombre', 'nEscanos')
	success_url = reverse_lazy('circunscripcion_url')

	def get_context_data(self, **kwargs):
		#obtenemos el contextode la clase base
		context = super(CircunscripcionCrear, self).get_context_data(**kwargs)
		#anyadimos nuevas variables de contexto al diccionario
		context['titulo'] = 'Crear Circunscripcion'
		context['nombre_btn'] = 'Crear'
		#devolvemos el contexto
		return context

class CircunscripcionDetalle(DetailView):
	model = Circunscripcion
	template_name = 'eleccion/vistaDetallada.html'

	def get_context_data(self, **kwargs):
		context = super(CircunscripcionDetalle, self).get_context_data(**kwargs)
		context['listadoMesas'] = Mesa.objects.filter(circunscripcion=self.kwargs['pk'])
		return context

class CircunscripcionEditar(UpdateView):
	template_name = 'eleccion/formulario.html'
	model = Circunscripcion
	fields = ('nombre', 'nEscanos')
	success_url = reverse_lazy('circunscripcion_url')

	def get_context_data(self, **kwargs):
		context = super(CircunscripcionEditar, self).get_context_data(**kwargs)
		context['titulo'] = 'Editar Circunscripcion'
		context['nombre_btn'] = 'Editar'
		return context

	def dispatch(self, request, *args, **kwargs):
		if not request.user.has_perm('eleccion.change_circunscripcion'):
			return redirect('circunscripcion_url')
		return super(CircunscripcionEditar,self).dispatch(request, *args, **kwargs)

class CircunscripcionEliminar(DeleteView):
	template_name = 'eleccion/eliminar.html'
	model = Circunscripcion
	success_url = reverse_lazy('circunscripcion_url')

	def dispatch(self, request, *args, **kwargs):
		if not request.user.has_perm('eleccion.delete_circunscripcion'):
			return redirect('login')
		return super(CircunscripcionEliminar, self).dispatch(request, *args, **kwargs)

#def CircunscripcionDelete(request, pk):
#	circunscripcion = Circunscripcion.objects.get(pk = pk)
#	if request.method == 'POST':
#		circunscripcion.delete()
#		return redirect('circunscripcion_url')
#	return render(request, 'eleccion/eliminar.html', { 'circunscripcion': circunscripcion })

def MesaDetalle(request, pk):
	mesa = Mesa.objects.get(pk= pk)
	return render(request, 'eleccion/vistaDetalladaMesa.html', { 'mesa': mesa })		

def MesaLista(request):
	mesa = Mesa.objects.all()[:10]
	return render(request,'eleccion/mesa.html', {'listadoMesa': mesa})

@login_required(login_url='login')
def MesaCrear(request):
	if request.method == 'POST':
		form = MesaForm(request.POST)
		if form.is_valid():
			mesa = form.save(commit=False)
			mesa.save()
			return redirect('mesa_url')
	else:
		form = MesaForm()
		return render(request,'eleccion/formulario.html', {'form': form, 'titulo': "Crear Mesa", 'nombre_btn': "Crear"})

@login_required(login_url='login')
def MesaEditar(request, pk):
	mesa = get_object_or_404(Mesa, pk=pk)
	if request.method == "POST":
		form = MesaForm(request.POST, instance=mesa)
		if form.is_valid():
			mesa = form.save(commit=False)
			mesa.save()
			return redirect('mesa_url')
	else:
		form = MesaForm(instance=mesa)
	return render(request, 'eleccion/formulario.html', {'form': form, 'titulo':"Editar Mesa", 'nombre_btn':"Editar"})

@login_required(login_url='login')
def MesaEliminar(request, pk):
	mesa = Mesa.objects.get(pk = pk)
	if request.method == 'POST':
		mesa.delete()
		return redirect('mesa_url')
	return render(request, 'eleccion/mesa_eliminar.html', {'mesa':mesa})



class ResultadoCrear(CreateView):
	template_name = 'eleccion/formulario.html'
	model = Resultado
	fields = ('partido', 'mesa', 'votos')
	success_url = reverse_lazy('resultado_url')

	def get_context_data(self, **kwargs):
	#obtener el contexto de la clase
		context = super(ResultadoCrear, self).get_context_data(**kwargs)
	#anyadimos nuevas variables de contexto al diccionario
		context['titulo'] = 'Crear Resultado'
		context['nombre_btn'] = 'Crear'
	#devolvemos el contexto
		return context

class ResultadoLista(ListView):
	model = Resultado
	template_name = "eleccion/resultado.html"

	def get_context_data(self, **kwargs):
		context = super(ResultadoLista, self).get_context_data(**kwargs)
		context['result_list'] = Resultado.objects.all()[:10]
		return context

class ResultadoEliminar(DeleteView):
	template_name = 'eleccion/eliminar_resultado.html'
	model = Resultado
	success_url = reverse_lazy('resultado_url')
	
	def get_context_data(self, **kwargs):
		context = super(ResultadoEliminar, self).get_context_data(**kwargs)
		context['titulo'] = 'Eliminar resultado'
		context['nombre_btn'] = 'Eliminar'
		return context

	def dispatch(self, request, *args, **kwargs):
		if not request.user.has_perm('eleccion.delete_resultado'):
			return redirect('login')
		return super(ResultadoEliminar,self).dispatch(request, *args, **kwargs)

class ResultadoEditar(UpdateView):
	template_name = 'eleccion/resultado_editar.html'
	model = Resultado
	fields = ('mesa', 'partido', 'votos')
	success_url = reverse_lazy('resultado_url')

	def get_context_data(self, **kwargs):
		context = super(ResultadoEditar, self).get_context_data(**kwargs)
		context['titulo'] = 'Editar Resultado'
		context['nombre_btn'] = 'Editar'
		return context

	def dispatch(self, request, *args, **kwargs):
		if not request.user.has_perms('eleccion.change_resultado'):
			return redirect('login')
		return super(ResultadoEditar, self).dispatch(request, *args, **kwargs)

elecciones/polls/templates/eleccion/circunscripcion.html
{% extends "eleccion/base.html" %}

    {% block content %}
    	<h1  class="page-header">Circunscripciones</h1>

        {% if perms.eleccion.change_circunscripcion %}
			<a href="{% url 'circunscripcion_crear_url' %}">Añadir Circunscripciones</a>
		{% endif %}


		<div class="row">
		{% if object_list %}
			{% for x in object_list %}
				<a href="{% url 'circunscripcion_detalle_url' x.id %}">
					<div class="col-md-2 cajaBlanca">
							<h4><strong>{{ x.nombre }}</strong></h4>
							<small>Escaños: </small> <strong>{{ x.nEscanos }}</strong>				
					</div>
					<a href="{% url 'circunscripcion_eliminar_url' x.id %}" class="btn btn-danger" role="button"><button type="button" class="btn btn-info">Eliminar</button></a>

				</a>
			{% endfor %}
		{% else %}
	    	<li>No hay circunscripciones aún.</li>
		{% endif %}

		</div>

    {% endblock %}

elecciones/polls/templates/eleccion/eliminar.html
{% extends 'eleccion/base.html' %}

    {% block content %}
        <form method="POST">
            {% csrf_token %}
            <h3>¿Seguro que quieres eliminar la entrada {{ circunscripcion.nombre }}?</h3>
            <div class="row">
          		<div class="col-md-4">
    	 	        <button type="submit" class="btn btn-danger" style="float:right">Si, eliminar</button>
    		        <a href="{% url 'circunscripcion_url' %}" class="btn btn-default" >Cancelar</a>       			
            	</div>
            </div>
        </form>
    {% endblock %}

elecciones/polls/templates/eleccion/eliminar_resultado.html
{% extends 'eleccion/base.html' %}

    {% block content %}
        <h1 class="page-header">Confirmación para eliminar {{ resultado.mesa }}</h1>
        <form method="post" action="">
            {% csrf_token %}
            <p>¿Seguro que quieres eliminar la entrada {{ resultado.mesa }}?</p>
            <div class="row">
          		<div class="col-md-4">
    	 	        <button type="submit" class="btn btn-danger" style="float:right">Si, eliminar</button>
    		        <a href="{% url 'resultado_url' %}" class="btn btn-default" >Cancelar</a>       			
            	</div>
            </div>
        </form>
    {% endblock %}

elecciones/polls/templates/eleccion/formulario.html
{% extends "eleccion/base.html" %}

{% block content %}
    <h1 class="page-header">{{ titulo }}</h1>
    <form role="form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{{ nombre_btn }}</button>
    </form>
    
{% endblock content %}

elecciones/polls/templates/eleccion/gracias.html
{% extends "eleccion/base.html" %}

{% block content %}
<div class="alert alert-success">
  <strong>{{ usuario }} gracias por registarte!</strong> 
</div>
<a href="{% url 'appJM:login' %}"><button type="submit" class="btn btn-primary">Login</button></a>
	
{% endblock content %}

elecciones/polls/templates/eleccion/index.html
{% extends "eleccion/base.html" %}

    {% block content %}
        <h1 class="page-header">Gestor Electoral</h1>

		{% if user.is_authenticated %}
        	<p>Ud. Está logueado como <strong style="color:#03bb03;">{{user.username}}</strong></p>
        {% else %}
        	<p>Ud. Está en modo <strong style="color:orange;">anónimo</strong>, para disfrutar de todas las opciones, por favor, identifíquese.</p>
        {% endif %}

        <div class="jumbotron">
        	<h1 class="display-3">Consideraciones generales</h2>
        	<p>Bienvenido al sistema de gestión electoral</p>

        </div>

    {% endblock %}

elecciones/polls/templates/eleccion/login.html
{% extends "eleccion/base.html" %}

    {% block content %}
        <h1 class="page-header">Login to Elecciones</h1>

        <div class="jumbotron">
            <h2 class="form-signin-heading">Por favor identifíquese</h2>

            <form id="login_form" method="post" action="/login/" class="form-signin">
                {% csrf_token %}
                <p>Usuario:</p><input class="form-control" placeholder="Nombre de usuario" type="text" name="username" value="" size="50" required autofocus=""/>
                <br />
                <p>Password:</p> <input class="form-control" placeholder="Password" type="password" name="password" value="" size="50" />
                <br />

                <input class="btn btn-primary" type="submit" value="Enviar" />
            </form>
        </div>
        
    {% endblock %}

elecciones/polls/templates/eleccion/mesa.html
{% extends "eleccion/base.html" %}

	{% block content %}
		<h1  class="page-header">Listado de Mesas</h1>

		{% if perms.eleccion.change_mesa %}
			<a href="{% url 'mesa_crear_url' %}">Añadir Mesa</a>
		{% endif %}


		<div class="row">

			{% for x in listadoMesa %}
				<a href="{% url 'mesa_detalle_url' x.id %}">
					<div class="col-md-2 cajaBlanca">
							<h4><strong>{{ x.nombre }}</strong></h4>
							<small>Escaños: </small> <strong>{{ x.nEscanos }}</strong>    		        					
					</div>
				</a>			
			{% empty %}
					<li>No hay mesas aún.</li>
			{% endfor %}

		</div>

	{% endblock %}

elecciones/polls/templates/eleccion/mesa_eliminar.html
{% extends 'eleccion/base.html' %}

    {% block content %}
        <form method="POST">
            {% csrf_token %}
            <h3>¿Seguro que quieres eliminar la entrada {{ mesa.nombre }}?</h3>
            <div class="row">
          		<div class="col-md-4">
    	 	        <button type="submit" class="btn btn-danger" style="float:right">Si, eliminar</button>
    		        <a href="{% url 'mesa_url' %}" class="btn btn-default" >Cancelar</a>       			
            	</div>
            </div>
        </form>
    {% endblock %}

elecciones/polls/templates/eleccion/no_activo.html
{% extends "eleccion/base.html" %}

{% load staticfiles %}

{% block content %}
<div class="alert alert-danger">
  <strong>El usuario no esta activo, contacte con el administrador para resolver el problema.</strong>
</div>

{% endblock %}

elecciones/polls/templates/eleccion/partido_eliminar.html
{% extends 'eleccion/base.html' %}

    {% block content %}
        <form method="POST">
            {% csrf_token %}
            <h3>¿Seguro que quieres eliminar la entrada {{ partido.nombre }}?</h3>
            <div class="row">
                <div class="col-md-4">
                    <button type="submit" class="btn btn-danger" style="float:right">Si, eliminar</button>
                    <a href="{% url 'partido_listar_url' %}" class="btn btn-default" >Cancelar</a>                 
                </div>
            </div>
        </form>
    {% endblock %}

elecciones/polls/templates/eleccion/registro.html
{% extends "eleccion/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="page-header">
                <h2>Registro Usuario</h2>
            </div>

            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
{% endblock %}

elecciones/polls/templates/eleccion/resultado.html
{% extends "eleccion/base.html" %}

    {% block content %}
    	<h1  class="page-header">Resultados</h1>

        {% if perms.eleccion.change_resultado %}
			<a href="{% url 'resultado_crear_url' %}">Añadir Resultado</a>
		{% endif %}
		
		<div class="row">
			
				<ul>
					{% for x in result_list %}
						<li>Partido: {{x.partido}}</li>
						<li>Mesa: {{x.mesa}}</li>
						<li>Nº Votos:  {{x.votos}}</li>
						{% if perms.eleccion.change_resultado %}
							<a href="{% url 'resultado_editar_url' x.id %}">Editar</a>
							<a href="{% url 'resultado_eliminar_url' x.id %}">Eliminar</a>
						{% endif %}
						<hr>		   		        								
					{% empty %}
						<li>No hay resultados aún.</li>
					{% endfor %}
				</ul>
		</div>

    {% endblock %}

    

elecciones/polls/templates/eleccion/resultado_editar.html
{% extends "eleccion/base.html" %}

{% block content %}
    <h1 class="page-header">{{ Editar }}</h1>
    <form role="form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{{ nombre_btn }}</button>
    </form>
    
{% endblock content %}